<?xml version="1.0" encoding="utf-8"?><Database Name="USERS" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-D1TJNIU;Initial Catalog=USERS;Integrated Security=True" SettingsObjectName="Bank_project.Properties.Settings" SettingsPropertyName="USERSConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bank" Member="Banks">
    <Type Name="Bank">
      <Column Name="Account_No" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Crd_NO" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Full_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Account_Balance" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Passward" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Phone_No" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Manager" Member="Managers">
    <Type Name="Manager">
      <Column Name="Manager_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Branch" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Full_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Passward" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Phone_No" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Accountent" Member="Accountents">
    <Type Name="Accountent">
      <Column Name="Accountent_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Full_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pin_no" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Phone_No" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>